import sqlalchemy as sa
from sqlalchemy.sql.elements import ColumnElement

from .policy import Command, Policy

# every per-request identity GUC this schema reads lives under this prefix, `app.uid` and
# `app.scope`, distinct from Postgres's own reserved settings namespaces.
GUC_SCHEMA = "app"

# Core table stand-ins for the visibility lattice, columns named but untyped, so a predicate can
# join against membership, groups, and principal without importing their mapped ORM classes; a
# mixin's predicates are built before its own concrete subclasses exist, and importing the model
# modules here would cycle back through `mixins` which every model itself imports.
MEMBERSHIP = sa.table(
    "membership", sa.column("principal_id"), sa.column("group_id"), sa.column("role")
)
GROUPS = sa.table("group_", sa.column("id"), sa.column("public"), sa.column("curated"))
PRINCIPAL = sa.table("principal", sa.column("id"), sa.column("is_admin"))


def guc(name: str) -> ColumnElement:
    """A scalar-subquery read of one `app.<name>` GUC, NULL when the session never set it.

    Wrapped in `SELECT` rather than called bare so Postgres plans the read as one InitPlan,
    evaluated once per query regardless of how many candidate rows the policy scans, instead of
    once per row a bare function call in the USING clause would cost. Labeled explicitly so the
    compiled text names a fixed column (`AS uid`, `AS scope`) rather than an autogenerated
    `anon_1`-style label whose exact spelling would depend on which other anonymous expressions
    share the same compile call, keeping the compiled predicate deterministic enough to pin in a
    test.

    name: the GUC's own name under the `app.` schema, `uid` or `scope`.
    """
    read = sa.func.nullif(sa.func.current_setting(f"{GUC_SCHEMA}.{name}", True), "")
    return sa.select(read.cast(sa.Uuid()).label(name)).scalar_subquery()


# the acting principal and the optional single-group reading lens, each read once and reused
# across every predicate below rather than rebuilt per table.
UID = guc("uid")
LENS = guc("scope")


def read_predicate(owner_id: ColumnElement, scope: ColumnElement) -> ColumnElement[bool]:
    """A row is readable when its scope matches a narrowed lens and the reader has standing.

    A narrowed session (`app.scope` set) only reads that one group's rows, the composed-graph lens
    that projects a single group's graph out of the union; an unnarrowed session reads everything
    standing already reaches. Standing itself is ownership, shared membership, or the scope
    belonging to a public group anyone may read.

    owner_id: the table's own owner column.
    scope: the table's own scope column.
    """
    return sa.and_(
        sa.or_(LENS.is_(None), scope == LENS),
        sa.or_(
            owner_id == UID,
            scope.in_(sa.select(MEMBERSHIP.c.group_id).where(MEMBERSHIP.c.principal_id == UID)),
            scope.in_(sa.select(GROUPS.c.id).where(GROUPS.c.public)),
        ),
    )


def write_predicate(owner_id: ColumnElement, scope: ColumnElement) -> ColumnElement[bool]:
    """A row is writable when it is the actor's own private row or a scope they write into.

    Visibility never implies write access: a reader member and a public-group visitor read the
    shared graph but cannot touch it, and ownership alone cannot publish into a scope, the moat the
    promote path relies on.

    owner_id: the table's own owner column.
    scope: the table's own scope column.
    """
    return sa.or_(
        sa.and_(scope.is_(None), owner_id == UID),
        scope.in_(
            sa.select(MEMBERSHIP.c.group_id).where(
                MEMBERSHIP.c.principal_id == UID, MEMBERSHIP.c.role.in_(("writer", "admin"))
            )
        ),
    )


def curation_admin_predicate(scope: ColumnElement) -> ColumnElement[bool]:
    """A curated-group row is reachable by any server-wide admin, membership or not.

    A curated group's canon is centrally governed, so a server admin may read and review its rows
    even without a membership row there, the standing `auth.groups.require_group_admin` already
    vouches for at the application layer before any of these rows are ever touched.

    scope: the table's own scope column.
    """
    return sa.and_(
        scope.in_(sa.select(GROUPS.c.id).where(GROUPS.c.curated)),
        sa.exists(sa.select(sa.literal(1)).where(PRINCIPAL.c.id == UID, PRINCIPAL.c.is_admin)),
    )


# bare stand-in for a content table's own primary key, the same table-unqualified trick
# `mixins.scoped.OWNER_ID`/`SCOPE` use, since a content table's policy names no table but itself.
CONTENT_ID = sa.column("id", sa.Uuid())


def content_visible_predicate(claim_table: str) -> ColumnElement[bool]:
    """A content row is visible when at least one of its claims is visible in its own right.

    Content carries no owner or scope of its own, so visibility derives through the claim table
    rather than a duplicated predicate here: `claim_table` is itself forced under row level
    security, so Postgres applies whichever policies it declares to this subquery's read.
    Deliberate, not incidental — a claim table's visible set is not always just `read_predicate`
    (`FactClaim` widens it with `curation_admin_policies`), so hand-rebuilding only the default
    predicate here would silently drop that wider reach.

    claim_table: name of the claim table joining content to its per-container stakes.
    """
    claims = sa.table(claim_table, sa.column("content_id"))
    return CONTENT_ID.in_(sa.select(claims.c.content_id))


def content_admin_predicate() -> ColumnElement[bool]:
    """Content is deletable only by a server-wide admin, the system merge's own escape.

    Content is immutable and carries no owner of its own, so no ordinary write predicate has a
    notion of "my content" to gate a delete on; only the system dedup merge, running as an admin
    principal, ever deletes a content row once its last claim is gone.
    """
    return sa.exists(sa.select(sa.literal(1)).where(PRINCIPAL.c.id == UID, PRINCIPAL.c.is_admin))


def content_policies(claim_table: str) -> list[Policy]:
    """The three policies a content table carries: visible through a claim, freely mintable,
    immutable, and deletable only by a system admin.

    A content row carries no UPDATE policy at all, so any UPDATE is denied outright under FORCE
    ROW LEVEL SECURITY, the database's own enforcement that content, once minted, never changes;
    INSERT is WITH CHECK true since minting content is harmless on its own, real access is gated
    at the claim a caller must separately hold to ever see it again.

    claim_table: name of the claim table this content is visible through.
    """
    return [
        Policy("content_read", Command.select, using=content_visible_predicate(claim_table)),
        Policy("content_insert", Command.insert, check=sa.true()),
        Policy("content_delete", Command.delete, using=content_admin_predicate()),
    ]


def default_scope_policies(owner_id: ColumnElement, scope: ColumnElement) -> list[Policy]:
    """The four per-command scope policies every `Scoped` table carries.

    The write predicate is split across per-command policies rather than one `FOR ALL` policy,
    since a `FOR ALL` policy's USING clause would also be OR-ed into SELECT visibility and leak
    writable rows past the read policy's narrowing lens.

    owner_id: the table's own owner column.
    scope: the table's own scope column.
    """
    read = read_predicate(owner_id, scope)
    write = write_predicate(owner_id, scope)
    return [
        Policy("scope_read", Command.select, using=read),
        Policy("scope_insert", Command.insert, check=write),
        Policy("scope_update", Command.update, using=write, check=write),
        Policy("scope_delete", Command.delete, using=write),
    ]


def curation_admin_policies(scope: ColumnElement) -> list[Policy]:
    """Supplemental SELECT, UPDATE, and DELETE policies letting a server admin govern curated rows.

    Postgres combines multiple PERMISSIVE policies for one command with OR, so these ride alongside
    `default_scope_policies`'s scope policies as an additive escape rather than replacing them: a
    group's own admin member keeps reaching its curated rows through the ordinary scope policies,
    and a global admin reaches any curated group's rows through these. INSERT carries no admin
    policy, since review only approves or rejects a row a member already wrote, never mints one.

    scope: the table's own scope column.
    """
    admin = curation_admin_predicate(scope)
    return [
        Policy("curation_admin_read", Command.select, using=admin),
        Policy("curation_admin_update", Command.update, using=admin, check=admin),
        Policy("curation_admin_delete", Command.delete, using=admin),
    ]
