-- The pgqueuer schema, dumped verbatim from the library's install on the Python side so a
-- drizzle-built database carries the identical queue either worker drains, plus the same
-- app-role grants the Python setup applies.
CREATE TYPE pgqueuer_status AS ENUM ('queued', 'picked', 'successful', 'exception', 'canceled', 'deleted', 'failed');--> statement-breakpoint
CREATE TABLE pgqueuer (
	id BIGSERIAL PRIMARY KEY,
	priority integer NOT NULL,
	queue_manager_id uuid,
	created timestamp with time zone DEFAULT now() NOT NULL,
	updated timestamp with time zone DEFAULT now() NOT NULL,
	heartbeat timestamp with time zone DEFAULT now() NOT NULL,
	execute_after timestamp with time zone DEFAULT now() NOT NULL,
	status pgqueuer_status NOT NULL,
	entrypoint text NOT NULL,
	dedupe_key text,
	payload bytea,
	headers jsonb,
	attempts integer DEFAULT 0 NOT NULL
);--> statement-breakpoint
CREATE TABLE pgqueuer_log (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created timestamp with time zone DEFAULT now() NOT NULL,
	job_id bigint NOT NULL,
	status pgqueuer_status NOT NULL,
	priority integer NOT NULL,
	entrypoint text NOT NULL,
	traceback jsonb,
	aggregated boolean DEFAULT false
);--> statement-breakpoint
CREATE TABLE pgqueuer_schedules (
	id BIGSERIAL PRIMARY KEY,
	expression text NOT NULL,
	entrypoint text NOT NULL,
	heartbeat timestamp with time zone DEFAULT now() NOT NULL,
	created timestamp with time zone DEFAULT now() NOT NULL,
	updated timestamp with time zone DEFAULT now() NOT NULL,
	next_run timestamp with time zone DEFAULT now() NOT NULL,
	last_run timestamp with time zone,
	status pgqueuer_status DEFAULT 'queued'::pgqueuer_status,
	UNIQUE (expression, entrypoint)
);--> statement-breakpoint
CREATE TABLE pgqueuer_statistics (
	id BIGSERIAL PRIMARY KEY,
	created timestamp with time zone DEFAULT date_trunc('sec'::text, (now() AT TIME ZONE 'UTC'::text)) NOT NULL,
	count bigint NOT NULL,
	priority integer NOT NULL,
	status pgqueuer_status NOT NULL,
	entrypoint text NOT NULL
);--> statement-breakpoint
CREATE INDEX pgqueuer_ep_ea_idx ON pgqueuer (entrypoint, execute_after) WHERE (status = 'queued'::pgqueuer_status);--> statement-breakpoint
CREATE INDEX pgqueuer_ep_prio_id_idx ON pgqueuer (entrypoint, priority DESC, id) WHERE (status = 'queued'::pgqueuer_status);--> statement-breakpoint
CREATE INDEX pgqueuer_priority_id_id1_idx ON pgqueuer (priority, id DESC) INCLUDE (id) WHERE (status = 'queued'::pgqueuer_status);--> statement-breakpoint
CREATE INDEX pgqueuer_updated_id_id1_idx ON pgqueuer (updated, id DESC) INCLUDE (id) WHERE (status = 'picked'::pgqueuer_status);--> statement-breakpoint
CREATE INDEX pgqueuer_queue_manager_id_idx ON pgqueuer (queue_manager_id) WHERE (queue_manager_id IS NOT NULL);--> statement-breakpoint
CREATE UNIQUE INDEX pgqueuer_unique_dedupe_key ON pgqueuer (dedupe_key) WHERE ((status = ANY (ARRAY['queued'::pgqueuer_status, 'picked'::pgqueuer_status])) AND (dedupe_key IS NOT NULL));--> statement-breakpoint
CREATE INDEX pgqueuer_log_created ON pgqueuer_log (created);--> statement-breakpoint
CREATE INDEX pgqueuer_log_job_id_status ON pgqueuer_log (job_id, created DESC);--> statement-breakpoint
CREATE INDEX pgqueuer_log_status ON pgqueuer_log (status);--> statement-breakpoint
CREATE INDEX pgqueuer_log_not_aggregated ON pgqueuer_log (entrypoint, priority, status, created) WHERE (NOT aggregated);--> statement-breakpoint
CREATE UNIQUE INDEX pgqueuer_statistics_unique_count ON pgqueuer_statistics (priority, date_trunc('sec'::text, (created AT TIME ZONE 'UTC'::text)), status, entrypoint);--> statement-breakpoint
CREATE FUNCTION fn_pgqueuer_changed() RETURNS TRIGGER AS $$
	DECLARE
		to_emit BOOLEAN := false;
	BEGIN
		IF TG_OP = 'UPDATE' AND OLD IS DISTINCT FROM NEW THEN
			to_emit := true;
		ELSIF TG_OP = 'DELETE' THEN
			to_emit := true;
		ELSIF TG_OP = 'INSERT' THEN
			to_emit := true;
		ELSIF TG_OP = 'TRUNCATE' THEN
			to_emit := true;
		END IF;
		IF to_emit THEN
			PERFORM pg_notify(
				'ch_pgqueuer',
				json_build_object(
					'channel', 'ch_pgqueuer',
					'operation', lower(TG_OP),
					'sent_at', NOW(),
					'table', TG_TABLE_NAME,
					'type', 'table_changed_event'
				)::text
			);
		END IF;
		IF TG_OP IN ('INSERT', 'UPDATE') THEN
			RETURN NEW;
		ELSIF TG_OP = 'DELETE' THEN
			RETURN OLD;
		END IF;
		RETURN NULL;
	END;
$$ LANGUAGE plpgsql;--> statement-breakpoint
CREATE TRIGGER tg_pgqueuer_changed
	AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON pgqueuer
	FOR EACH STATEMENT EXECUTE FUNCTION fn_pgqueuer_changed();--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON pgqueuer, pgqueuer_log, pgqueuer_statistics, pgqueuer_schedules TO aizk_app;--> statement-breakpoint
GRANT USAGE, SELECT ON SEQUENCE pgqueuer_id_seq, pgqueuer_log_id_seq, pgqueuer_statistics_id_seq, pgqueuer_schedules_id_seq TO aizk_app;
